### ISSUE TITLE
how can i do with Websocket protocol not supported ?

### ISSUE THREAD

**Issue by tuierbufei** [Atmosphere/atmosphere-samples#33]
I use gwt20 manage rpc and i want set the transport is websocket and fallbackTransport is long-polling, i run it on Firefox/24.0 and Chrome/34.0, My problem is that both of them have error, only i can user transport is long-polling.
the log as follows:
[ERROR] 501 - GET /ichangtougame/atmosphere/gameshostersevice/?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.0.3-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&X-Cache-Date=0&Content-Type=text/x-gwt-rpc;%20charset=UTF-8&X-atmo-protocol=true (127.0.0.1)
   Request headers
      Upgrade: websocket
      Connection: Upgrade
      Host: 127.0.0.1:8888
      Origin: http://127.0.0.1:8888
      Pragma: no-cache
      Cache-Control: no-cache
      Sec-WebSocket-Key: IUUoEk9jEBpvNWsgVCsPgw==
      Sec-WebSocket-Version: 13
      Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits, x-webkit-deflate-frame
      User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36
   Response headers
      X-Atmosphere-tracking-id: 95cfc5b0-1984-448d-a6e4-2f97fe371d40
      X-Atmosphere-error: Websocket protocol not supported
It seem that Websocket protocol not supported, whether i need configure something?
can anyone help me.

**Comment by dms120** [comment]
Hi @jfarcand that group is offline. What can i do to avoid the error?
I'm trying to upgrade from version 2.1.14 and i'm getting the "Websocket protocol not supported".

Thanks in advance.
