### ISSUE TITLE
atmosphere-jersey-pubsub and Tomcat 8.0.15

### ISSUE THREAD

**Issue by kayz1** [Atmosphere/atmosphere-samples#40]
Status code higher or equal than 400. Unable to deliver the websocket messages to installed component. Status 404 Message Not Found

Windows 7, x64
Java 1.8.0_25, x64
Tomcat 8.0.15 or 8.0.17, x64

It's working on Tomcat 7.0.57.

**Comment by jfarcand** [comment]
Good catch, fixed by https://github.com/Atmosphere/atmosphere/issues/1838
