### ISSUE TITLE
bringing back twitter-live-feed sample

### ISSUE THREAD

**Issue by elakito** [Atmosphere/atmosphere-samples#41]

**Comment by elakito** [comment]
@jfarcand 
as mentioned in ML, I am pushing this version that does the feed part right but fails to handle the stop part.
before running this sample, you need to add your consumer key to the web.xml

**Comment by rcampion** [comment]
twitter-live-feed sample does not work on Tomcat 8.5.15.  404 errors for JavaScript files.
