### ISSUE TITLE
Upgrade to jackson2

### ISSUE THREAD

**Issue by elakito** [Atmosphere/atmosphere-samples#43]
We can upgrade Amosphere 2.3.x samples to use jackson2 instead of jackson 1.x.

**Comment by elakito** [comment]
it seem like we should be upgrading atmosphere-extenions to use jackson2 as well.

**Comment by jfarcand** [comment]
:+1:

**Comment by elakito** [comment]
atmosphere-extension 2.3.0 has been upgraded with
https://github.com/Atmosphere/atmosphere-extensions/issues/180
