### ISSUE TITLE
2.3.0-SNAPSHOT is referenced in samples but does not exist in maven

### ISSUE THREAD

**Issue by Jazzepi** [Atmosphere/atmosphere-samples#45]
Neither atmosphere or the atmosphere extension mentioned in the base pom.xml exist in maven. This makes the sample unbuildable.

    <atmosphere-version>2.3.0-SNAPSHOT</atmosphere-version>
    <extensions-version>2.3.0-SNAPSHOT</extensions-version>

**Comment by jfarcand** [comment]
@Jazzepi ? Check properly :-)

**Comment by jfarcand** [comment]
https://buildhive.cloudbees.com/view/My%20Repositories/job/Atmosphere/job/atmosphere-samples/

**Comment by Jazzepi** [comment]
My apologizes. I couldn't get it to build at work, but trying it out it builds okay on my machine at home. I'm sure there was something at work getting in the way.

**Comment by jfarcand** [comment]
@Jazzepi No problem!
