### ISSUE TITLE
four in a row apps are broken. raised three issues. very disappointed. you should be worried. 

### ISSUE THREAD

**Issue by simbo1905** [Atmosphere/atmosphere-samples#54]
I grabbed the zip and tried four samples in a row. none of them worked. I raised issues against three of them. 

I was excited about idea of atmosphere as it seems to be 'write once, run everywhere' but the quality of these samples is 'write once, broke everywhere'. 

I know that this is opensource and stuff gets bit rot and sometimes things break and that folks like me should send a PR. However if I were the company selling commercial support for this though I would be really worried about the message that this is sending out. A few apps that really work is a good thing. A huge amount of apps where four in a row picked at random and are broken is such a bad thing that you need to take them offline until you get them fixed. 

Maybe I will try again tomorrow but right now I just want to walk away and not come back. 

:-1:

**Comment by jfarcand** [comment]
Great, beacuse you are completely off track with your testing :-) Everything works as expected, you just don't know what you are doing.
