### ISSUE TITLE
chat sample doesnt work

### ISSUE THREAD

**Issue by chriswadeWol** [Atmosphere/atmosphere-samples#69]
I cant get the chat example to run, netbeans and jdeveloper both fail when trying to deploy that sample.
Is their anything that is not in the tutorials that I need to do?

Is There a download of a full working example?

**Comment by ndm250** [comment]
Please include any error messages you may be experiencing, otherwise we can't help you.

I had problems with the deployment descriptor in one of the chat samples before, check out this issue: 
https://github.com/Atmosphere/atmosphere-samples/issues/64

**Comment by javydreamercsw** [comment]
It worked fine for me on Netbeans. Worked out of the box.
